name: Coverity analysis

on:
  push:
    branches: [ coverity_scan ]

jobs:
  coverity:
    name: Run Coverity tests
    if: github.repository == 'web-eid/web-eid-authtoken-validation-java'
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
      PROJECTNAME: 'web-eid/web-eid-authtoken-validation-java'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v8-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v8

      - name: Download Coverity Build Tool
        run: |
          curl --silent --data "token=$TOKEN&project=$PROJECTNAME" -o cov-analysis-linux64.tar.gz https://scan.coverity.com/download/cxx/linux64
          mkdir cov-analysis-linux64
          tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64

      - name: Build
        run: |
          export PATH=$PWD/cov-analysis-linux64/bin:$PATH
          cov-build --dir cov-int mvn --batch-mode compile

      - name: Submit the result to Coverity Scan
        run: |
          tar czvf upload.tgz cov-int
          curl --silent \
            --form project=$PROJECTNAME \
            --form token=$TOKEN \
            --form email=eid-teenusehaldus@ria.ee \
            --form file=@upload.tgz \
            --form version=master \
            --form description="Github Actions CI build" \
            https://scan.coverity.com/builds?project=$PROJECTNAME